.PHONY: clean All

All:
	@echo "----------Building project:[ frugally-deep - Debug ]----------"
	@"$(MAKE)" -f  "frugally-deep.mk"
clean:
	@echo "----------Cleaning project:[ frugally-deep - Debug ]----------"
	@"$(MAKE)" -f  "frugally-deep.mk" clean
